<?php

/**
 * Ecuador places
 *
 * @author   Saul Morales Pacheco <moralespachecopablo@gmail.com>
 * @version  2.0.7
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['EC'] = array(
	'MAN' => array(
		"10 De Agosto",
		"24 De Mayo",
		"Arenales",
		"Atahualpa Manabi",
		"Bachillero",
		"Bellavista",
		"Calceta",
		"Calderon (Manabi)",
		"Canoa",
		"Canuto",
		"Cañitas",
		"Cascol",
		"Charapoto",
		"Cheve",
		"Ciudad Alfaro",
		"Coaque",
		"Cojimies",
		"Colon",
		"Colorado",
		"Crucita",
		"Don Juan",
		"El Carmen",
		"El Matal",
		"El Rodeo",
		"Flavio Alfaro",
		"Jama",
		"Jaramijo",
		"Junin",
		"La Chorrera",
		"La Estancilla",
		"Leonidas Plaza",
		"Lodana",
		"Los Bajos",
		"Machalilla",
		"Mache",
		"Montecristi",
		"Nuevo Briceño",
		"Olmedo (Manabi)",
		"Pajan",
		"Pedernales",
		"Pichincha",
		"Playa Prieta",
		"Pueblo Nuevo (Manabi)",
		"Puerto Lopez",
		"Ricaurte (Manabi)",
		"Rio Chico",
		"Rocafuerte",
		"San Antonio (Manabi)",
		"San Clemente",
		"San Isidro (Bahia)",
		"San Jacinto",
		"San Placido",
		"San Vicente",
		"Sancan",
		"Santa Ana (Manabi)",
		"Sosote",
		"Sucre - Bahia",
		"Tosagua",
		"Bahia De Caraquez",
		"Chone",
		"Jipijapa",
		"Manta",
		"Portoviejo"
		),
	'AZG' => array(
		"Cojitambo"
		),
	'AZU' => array(
		"Baños (Azuay)",
		"Chordeleg",
		"Cumbe",
		"El Pan",
		"Giron",
		"Guachapala",
		"La Union (Azuay)",
		"Paute",
		"Ponce Enriquez",
		"Ricaurte (Azuay)",
		"San Fernando",
		"Santa Isabel",
		"Sevilla De Oro",
		"Sigsig",
		"Tarqui (Azuay)",
		"Cuenca",
		"Gualaceo"
		),
	'BOL' => array(
		"1Ero De Mayo",
		"4 Esquinas",
		"Asuncion",
		"Balzapamba",
		"Caluma",
		"Chillanes",
		"Chimbo",
		"La Magdalena ",
		"Pisagua Alto",
		"Pisagua Bajo",
		"Recinto 24 De Mayo",
		"Recinto El Palmar",
		"Recinto La Maritza",
		"Salinas (Bolivar)",
		"San Jose De Chimbo",
		"San Lorenzo ",
		"San Miguel De Bolivar",
		"San Pablo De Atenas",
		"San Pedro De Guanujo",
		"San Simon",
		"Santa Fe",
		"Vinchoa ",
		"Guaranda"
		),
	'CAN' => array(
		"Biblian",
		"Cañar",
		"Cochancay",
		"Deleg (Azuay)",
		"Ducur",
		"Guapan",
		"Ingapirca",
		"Javier Loyola",
		"La Puntilla - El Triunfo",
		"La Troncal",
		"Suscal",
		"Tambo",
		"Voluntad De Dios",
		"Azogues"
		),
	'CAR' => array(
		"Bolivar",
		"Chitan De Navarretes",
		"Cristobal Colon",
		"Cuesaca",
		"El Angel",
		"Garcia Moreno",
		"Huaca",
		"Julio Andrade",
		"La Paz",
		"Mira",
		"San Gabriel",
		"San Isidro (Carchi San Gabriel)",
		"Tulcan"
		),
	'GAB' => array(
		"Pioter",
		"Sandial",
		"Santa Martha De Cuba"
		),
	'CHI' => array(
		"Cajabamba",
		"Chambo",
		"Chunchi",
		"Colta",
		"El Guano",
		"Guamote",
		"Lican",
		"Pallatanga",
		"Penipe",
		"San Andres",
		"San Luis (Chimborazo)",
		"Yaruquies",
		"Alausi",
		"Riobamba"
		),
	'COT' => array(
		"Anchilivi",
		"Belisario Quevedo",
		"Chipualo",
		"El Corazon",
		"Guaytacama",
		"La Mana",
		"La Victoria",
		"Lasso",
		"Moraspungo",
		"Mulalao",
		"Mulalillo",
		"Pangua",
		"Panzaleo",
		"Pastocalle",
		"Patain",
		"Poalo",
		"Pujili",
		"Rumipamba",
		"Salcedo",
		"San Marcos",
		"Santa Ana (Cotopaxi)",
		"Saquisili",
		"Sigchos",
		"Tanicuchi",
		"Toacaso",
		"Yanayacu",
		"Latacunga"
		),
	'ORO' => array(
		"3 Cerritos (Pasaje)",
		"Arenillas",
		"Bajo Alto",
		"Balsas",
		"Barbones",
		"Bellamaria",
		"Buena Vista",
		"Caña Quemada",
		"El Cambio",
		"El Guabo",
		"El Pache",
		"El Porton",
		"La Avanzada",
		"La Iberia",
		"La Peaña",
		"Loma De Franco",
		"Lourdes",
		"Marcabeli",
		"Nuevo Puente Internacional Cebef",
		"Pasaje",
		"Piñas",
		"Portovelo",
		"Puerto Bolivar",
		"Puerto Hualtaco",
		"Puerto Jeli",
		"Rio Bonito",
		"San Vicente Del Jobo",
		"Santa Rosa (El Oro)",
		"Shumiral",
		"Zaruma",
		"Huaquillas",
		"Machala"
		),
	'ESM' => array(
		"Atacames",
		"Borbon",
		"La Concordia",
		"La Independencia",
		"La Union (Quininde)",
		"La Y De Calderon",
		"Lagarto",
		"Las Peñas ",
		"Muisne",
		"Quininde",
		"Rio Verde",
		"Same",
		"San Lorenzo",
		"Sua",
		"Tachina",
		"Tonchigue",
		"Tonsupa",
		"Viche",
		"Esmeraldas"
		),
	'GUA' => array(
		"3 Postes",
		"Alfredo Baquerizo Moreno",
		"Balao (Naranjal)",
		"Balao Chico (Naranjal)",
		"Balzar",
		"Base Taura",
		"Boca De Caña",
		"Boliche",
		"Bucay",
		"Cerecita",
		"Chiveria",
		"Cien Familia",
		"Colimes",
		"Coloradal",
		"Cumanda",
		"Data De Playas",
		"El Deseo",
		"El Empalme",
		"El Morro",
		"El Nato",
		"Engabao",
		"General Antonio Elizalde",
		"General Vernaza",
		"Ingenio San Carlos",
		"Isidro Ayora",
		"Jujan",
		"Km 26 - Virgen De Fatima",
		"La Maravilla",
		"La T De Salitre",
		"La Toma (Guayas)",
		"Las Animas",
		"Las Mercedes (Naranjal)",
		"Laurel",
		"Lomas De Sargentillo",
		"Lorenzo De Garaicoa",
		"Los Tintos",
		"Manuel J Calle",
		"Marcelino Maridueña",
		"Mariscal Sucre",
		"Matilde Esther",
		"Naranjal",
		"Naranjito",
		"Nobol",
		"Nueva Union (Naranjal)",
		"Palestina",
		"Pedro Carbo",
		"Petrillo",
		"Playas",
		"Posorja",
		"Progreso",
		"Puente Lucia",
		"Puerto Del Engabao",
		"Puerto Inca",
		"Roberto Astudillo",
		"Sabanilla (Pedro Carbo)",
		"Salitre - Urbina Jado",
		"Samborondon",
		"San Antonio (Playas)",
		"San Carlos (Balao)",
		"San Isidro (Guayas)",
		"San Jacinto De Yaguachi ",
		"Santa Lucia",
		"Santa Rita (Balao)",
		"Simon Bolivar",
		"Tarifa",
		"Tenguel",
		"Villa Nueva",
		"Virgen De Fatima Km 26",
		"Yaguachi",
		"Chongon",
		"Daule",
		"Duran - Eloy Alfaro",
		"El Triunfo",
		"Eloy Alfaro - Duran",
		"Milagro",
		"Urbina Jado - Salitre",
		"Guayaquil",
		"La Puntilla"
		),
	'IMB' => array(
		"Aduana",
		"Alpachaca",
		"Andrade Marin",
		"Antonio Ante",
		"Atuntaqui",
		"Caranqui",
		"Chaltura",
		"Chorlavi",
		"Cotacachi",
		"El Olivo",
		"El Retorno",
		"Natabuela",
		"Otavalo",
		"Pimampiro",
		"Pinsaqui",
		"Puerto Lago",
		"Quiroga",
		"San Antonio De Ibarra",
		"San Jose",
		"San Luis (Imbabura)",
		"San Pablo Del Lago",
		"San Roque",
		"Santo Domingo Imbabura",
		"Urcuqui",
		"Yachai",
		"Yaguarcocha",
		"Ibarra"
		),
	'LOJ' => array(
		"Alamor",
		"Cariamanga",
		"Catacocha",
		"Catamayo",
		"Celica",
		"Chaguarpamba",
		"Gonzanama",
		"Macara",
		"Malacatos",
		"Olmedo (Loja)",
		"Pindal",
		"Pozul",
		"San Lucas",
		"Santiago",
		"Saraguro",
		"Vilcabamba",
		"Zapotillo",
		"Loja",
		"Sozoranga"
		),
	'RIO' => array(
		"Baba",
		"Buena Fe",
		"Caracol",
		"Catarama",
		"Echeandia",
		"Entrada De San Juan",
		"Fumisa",
		"Hidrolitoral",
		"Isla De Bejucal",
		"La 14 Via El Paraiso",
		"La Esperanza",
		"La Julia",
		"La Union (Babahoyo)",
		"La Union (Valencia)",
		"Las Naves",
		"Los Angeles - Recinto",
		"Mata De Cacao",
		"Mocache",
		"Montalvo",
		"Nueva Union (Los Rios)",
		"Palenque",
		"Palmisa",
		"Patricia Pilar",
		"Pueblo Nuevo (Los Rios)",
		"Pueblo Viejo",
		"Quinsaloma",
		"Ricaurte (Los Rios)",
		"San Camilo",
		"San Carlos (Los Rios)",
		"San Juan",
		"San Luis De Pambil",
		"Urdaneta",
		"Valencia",
		"Vinces",
		"Zapotal (Los Rios)",
		"Zulema",
		"Babahoyo",
		"Quevedo",
		"Ventanas"
		),
	'MOR' => array(
		"Gualaquiza",
		"Limon Indanza",
		"Macas",
		"Mendez",
		"Palora",
		"Sucua"
		),
	'NAP' => array(
		"Archidona",
		"Arosemena Tola",
		"Baeza",
		"Borja",
		"Cotundo",
		"El Chaco",
		"Gonzalo Pizarro",
		"Nueva Esperanza",
		"Puerto Napo",
		"Tazayacu",
		"Tena"
		),
	'ORE' => array(
		"El Coca - Francisco De Orellana",
		"Joya De Los Sachas",
		"Loreto"
		),
	'PAS' => array(
		"Mera",
		"Puyo",
		"Santa Clara",
		"Shell (El Puyo)"
		),
	'PIC' => array(
		"Alangasi",
		"Aloag",
		"Aloasi",
		"Amaguaña",
		"Ayora",
		"Calacali",
		"Calderon (Pichincha)",
		"Conocoto",
		"Cumbaya",
		"Cusubamba",
		"Guachala",
		"Guayllabamba",
		"Juan Montalvo",
		"La Armenia",
		"Mejia",
		"Miravalle",
		"Monjas",
		"Nanegalito",
		"Pedro Vicente Maldonado",
		"Pifo",
		"Pintag",
		"Puembo",
		"Puerto Quito",
		"Quinche",
		"San Miguel De Los Bancos",
		"San Rafael",
		"Sangolqui",
		"Tabacundo",
		"Tambillo",
		"Cayambe",
		"Llano Chico",
		"Llano Grande",
		"Machachi",
		"Pomasqui",
		"Pusuqui",
		"Quito",
		"San Antonio De Pichincha",
		"San Jose De Moran",
		"San Juan De Calderon",
		"Tababela",
		"Uyumbicho",
		"Zambisa"
		),
	'ELE' => array(
		"Ancon",
		"Anconcito",
		"Ballenita",
		"Cadeate",
		"Capaes",
		"El Tambo",
		"Jambeli Monteverde (Santa Elena)",
		"Libertador Bolivar",
		"Manglaralto",
		"Montañita",
		"Monteverde - Jambeli (Santa Elena)",
		"Muey",
		"Olon",
		"Palmar",
		"Prosperidad",
		"Punta Barandua",
		"Punta Blanca",
		"Punta Carnero",
		"Punta Centinela",
		"Salinas (Santa Elena)",
		"San Pablo (Santa Elena)",
		"San Pedro",
		"Santa Rosa (Santa Elena)",
		"Valdivia",
		"La Libertad",
		"Santa Elena"
		),
	'TSA' => array(
		"Alluriquin",
		"Km 14-Quevedo",
		"Km 24-Quevedo",
		"Km 38.5 Via Quevedo",
		"Km 41 Via Quevedo",
		"Las Delicias",
		"Luz De America",
		"Nuevo Israel",
		"Puerto Limon",
		"San Jacinto Del Bua",
		"Valle Hermoso",
		"Santo Domingo"
		),
	'SUC' => array(
		"7 De Julio",
		"Cascales",
		"Jivino Verde",
		"Lago Agrio",
		"Los Rios (Sucumbios)",
		"Lumbaqui",
		"Reventador",
		"Santa Cecilia",
		"Shushufindi"
		),
	'TUN' => array(
		"Cevallos",
		"Huambalo",
		"Mocha",
		"Patate",
		"Pelileo",
		"Pillaro",
		"Quero",
		"Santa Rosa (Ambato)",
		"Tisaleo",
		"Ambato",
		"Baños (Tungurahua)"
		),
	'ZAM' => array(
		"El Pangui",
		"Palanda",
		"Yantzaza",
		"Zamora",
		"Zumba"
		)
	);